version: '3.1'

services:
  mysql:
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=mysqlpassword
    ports:
     - "3306:3306"
    volumes:
     - './zabbix/mysql:/var/lib/data'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    links: 
      - mysql
    restart: always
    ports: 
      - '10051:10051'
    volumes: 
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=mysqlpassword
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=mysqlpassword
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
        vpcbr:
          ipv4_address: 10.5.0.9
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16